# Generated by Django 4.1 on 2023-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.CharField(
                choices=[("Doctor", "doctor"), ("Patient", "patient")],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
