# Generated by Django 4.1 on 2024-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_patient_doctor_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_drafted",
            field=models.BooleanField(default=False),
        ),
    ]
