# Generated by Django 4.1 on 2023-11-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Salary", models.PositiveBigIntegerField()),
                ("Ddesignation", models.CharField(max_length=15)),
                ("Address", models.TextField()),
            ],
        ),
    ]
